# Generated by Django 5.2 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('reserved', 'Reservasi'), ('occupied', 'Tidak Tersedia'), ('maintenance', 'Perbaikan')], default='available', max_length=20),
        ),
    ]
