# Generated by Django 5.2 on 2025-11-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_spot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10, unique=True)),
                ('distance', models.FloatField(default=0)),
                ('status', models.CharField(default='Kosong', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
