# Generated by Django 5.2 on 2025-11-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_realtimespot'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimespot',
            name='buzzer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtimespot',
            name='distance',
            field=models.FloatField(default=0, help_text='Jarak objek ke sensor'),
        ),
        migrations.AlterField(
            model_name='realtimespot',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Terisi', 'Terisi'), ('Disabled', 'Perbaikan/Acara')], default='Kosong', max_length=20),
        ),
    ]
