# Generated by Django 5.2 on 2025-11-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_realtimespot_buzzer_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('slot_numbers', models.CharField(help_text='Contoh: 1, 2, 5-8', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label_color', models.CharField(choices=[('yellow', 'Kuning'), ('red', 'Merah'), ('gray', 'Abu-abu')], default='yellow', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
