# Generated by Django 5.2 on 2025-12-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='buzzer_muted',
            field=models.BooleanField(default=False),
        ),
    ]
