# Generated by Django 5.2 on 2026-07-09 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_spot_buzzer_muted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(help_text='Waktu mobil masuk / sensor mendeteksi Terisi')),
                ('end_time', models.DateTimeField(blank=True, help_text='Waktu mobil keluar', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Durasi parkir dalam menit', null=True)),
            ],
        ),
    ]
